services:
  jenkins:
     image: jenkins/jenkins:lts
     privileged: true
     user: root
     container_name: jenkins
     ports:
      - 8080:8080
     volumes:
      - /opt/jenkins/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock